# Generated by Django 5.1.4 on 2024-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Spanish', 'Spanish'), ('English', 'English')], max_length=100)),
                ('due_date', models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Spanish', 'Spanish'), ('English', 'English')], max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
