# Generated by Django 5.1.4 on 2024-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_homework_options_alter_homework_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
